FROM sabotagecla6/ubuntu-gui-jp

# ***********************************************
# install packages
# ***********************************************
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        python3 python3-pip

CMD ["/bin/bash"]
