FROM sabotagecla6/ubuntu-gui:20.04

# ***********************************************
# install wine
# ***********************************************
RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y \
        language-pack-ja-base language-pack-ja fonts-noto-cjk ibus-mozc

# ***********************************************
# set local
# ***********************************************
RUN update-locale LANG=ja_JP.UTF-8

ENV GTK_IM_MODULE=xim \
    QT_IM_MODULE=xim \
    XMODIFIERS=@im=ibus \
    DefalutIMModule=ibus

RUN locale-gen ja_JP.UTF-8  

ENV LANG=ja_JP.UTF-8 \
    LC_ALL=ja_JP.UTF-8

# ***********************************************
# setting keyboard layout
# ***********************************************
RUN { \
      echo 'XKBMODEL="pc105"'; \
      echo 'XKBLAYOUT="jp""'; \
      echo 'XKBVARIANT=""'; \
      echo 'XKBOPTIONS=""'; \
      echo ''; \
      echo 'BACKSPACE="guess"'; \
    } > /etc/default/keyboard

ENTRYPOINT ["/opt/endpoint.sh"]
CMD ["/bin/bash"]
